# 파이썬 기본

## 1.1 사칙연상의 이용

In [1]:
+ 2

2

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

## 1.2 제곱

In [3]:
2 ** 8

256

## 2.1 변수를 이용한 계산

In [5]:
x = 1
y = 1 / 3
x + y

1.3333333333333333

## 2.2 변수명의 표기

In [6]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

## 3.2 type으로 자료형 알아보기

In [7]:
type(100)

int

In [8]:
x = 100
type(x)

int

In [9]:
type(100.1)

float

In [10]:
x = 100.1
type(x)

float

## 3.3 문자열

In [11]:
x = 'learning'
type(x)

str

## 4.1 print 문의 이용

In [12]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


## 4.2 문자열과 수치를 함께 표시 1

In [13]:
print('x = ' + str(x))

x = 0.3333333333333333


## 4.3 문자열과 수치를 함께 표시 2

In [15]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


In [16]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print('weight: {0} kg {1} kg {2} kg'.format(x, y, z))

weight: 0.3333333333333333 kg 0.14285714285714285 kg 0.25 kg


In [18]:
print('weight: {0:.2f} kg, y = {1:.2f} kg, z = {2:.2f} kg'.format(x, y, z))

weight: 0.33 kg, y = 0.14 kg, z = 0.25 kg


## 5.1 list의 이용

In [31]:
x = [1, 1, 2, 3, 5] # list 정의
print(x) # list 표시

[1, 1, 2, 3, 5]


In [32]:
x[0]

1

In [33]:
x[2]

2

In [34]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


## 5.2 2차원 배열

In [35]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [36]:
x = [1, 1, 2, 3, 5]

In [37]:
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


## 5.3 list의 길이

In [38]:
x = [1, 1, 2, 3, 5]
len(x)

5

## 5.4 연속된 정수 데이터의 작성

In [39]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


In [40]:
z = list(range(5, 10))

In [41]:
print(z)

[5, 6, 7, 8, 9]


In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 6.1 tuple의 이용

In [43]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


## 6.2 요소의 참조

In [44]:
a[1]

2

In [45]:
type(a)

tuple

## 6.3 길이가 1인 tuple

In [46]:
a = (1)
type(a)

int

In [47]:
a = (1, )
type(a)

tuple

## 7.1 if 문의 사용

In [48]:
x = 11
if x > 10:
  print(' x is ' ) # ... (A1)
  print('          larger than 10.') # ... (A2)
else :
  print('x is smaller than 11') # ... (B1)

 x is 
          larger than 10.


## 7.2 비교 연산자

In [49]:
x = 15
if 10 <= x and x <= 20 :
  print('x is between 10 and 20.')

x is between 10 and 20.


## 8.1 for 문의 이용

In [50]:
for i in [1, 2, 3]:
  print(i)

1
2
3


## 8.2 enumerate의 이용

In [51]:
num = [2, 4, 6, 8, 10]

for i, n in enumerate(num) :
  num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


## 9.1 넘파이의 이용

In [52]:
import numpy as np

## 9.2 벡터의 정의

In [53]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [54]:
type(x)

numpy.ndarray

## 9.3 요소의 참조

In [55]:
x[0]

1

## 9.4 요소의  수정

In [56]:
x[0] = 100
print(x)

[100   2   3]


## 9.5 연속된 정수 벡터의 생성

In [58]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## 9.6 ndarray 형의 주의점

In [59]:
a = np.array([1, 1])
b = a.copy()

print('a = ' + str(a))
print('b = ' + str(b))


b[0] = 100

print('b = ' + str(b))
print('a = ' + str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [1 1]


In [60]:
a = np.array([1, 1])
b = a

print('a = ' + str(a))
print('b = ' + str(b))


b[0] = 100

print('b = ' + str(b))
print('a = ' + str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [100   1]


## 10.1 행렬의 정의

In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


## 10.2 행렬의 크기

In [62]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

## 10.3 요소의 참조

In [63]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]

6

## 10.4 요소의 수정

In [64]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


## 10.5 요소가 0과 1인 ndarray 만들기

In [65]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [67]:
print(np.ones((2, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 10.6 요소가 랜덤인 행렬 생성

In [68]:
np.random.rand(2, 3)

array([[0.51819196, 0.24491514, 0.20473362],
       [0.90122152, 0.74065442, 0.02242002]])

## 10.7 행렬의 크기 변경

In [69]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [70]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 11.1 행렬의 사칙 연산

In [71]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


## 11.2 스칼라 x 행렬

In [73]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


## 11.3 산술 함수

In [74]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(x)

[[4 4 4]
 [8 8 8]]


In [75]:
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


## 11.4 행렬 곱의 계산

In [76]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v)
print(w)

[[1 2 3]
 [4 5 6]]
[[1 1]
 [2 2]
 [3 3]]


In [77]:
print(v.dot(w))

[[14 14]
 [32 32]]


## 12.1 슬라이싱의 이용

In [78]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [79]:
print(x[5:])

[5 6 7 8 9]


In [80]:
print(x[3:8:2])

[3 5 7]


In [81]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


## 13.1 bool 배열 사용

In [84]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [85]:
x[ x > 3 ]

array([ 5,  8, 13])

In [86]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


## 14.1 Help 사용

In [91]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

### colab help 기능

In [93]:
np.random.randint?

## 15.1 함수의 사용

In [94]:
def my_func1():
  print('Hi!')
# 함수 my_func1()의 정의는 여기까지

my_func1() # 함수를 실행

Hi!


In [95]:
def my_func2(a, b):
  c = a + b
  return c

my_func2(1, 2)

3

## 15.2 인수와 반환값

In [96]:
def my_func3(D):
  m = np.mean(D)
  s = np.std(D)
  return m, s

In [98]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)

print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean:0.07, std:1.04


## 16.1 하나의 ndarray 형을 저장

In [99]:
data = np.random.randn(5)
print(data)

# 파일저장
np.save('datafile.npy', data)

# data 삭제
data = []
print(data)

# 파일로드
data = np.load('datafile.npy')
print(data)

[ 0.87659579  1.53396575 -1.27449916 -1.28623137 -0.80461705]
[]
[ 0.87659579  1.53396575 -1.27449916 -1.28623137 -0.80461705]


## 16.2 여러 ndarray 형을 저장

In [100]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1 = data1, data2 = data2) # 파일저장

# data 삭제
data1 = []
data2 = []

# 파일로드
outfile = np.load('datafile2.npz')
print(outfile.files) # 저장된 데이터 표시
data1 = outfile['data1'] # data1 꺼내기
data2 = outfile['data2'] # data2 꺼내기

print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
